# Generated by Django 3.1.3 on 2020-11-03 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201102_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Величина счета, Rub'),
        ),
    ]
